version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./app:/app/app  # For development hot-reload
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DATABASE_URL=sqlite:///./data/urls.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/monitoring/health"]
      interval: 30s
      timeout: 10s
      retries: 3