name: Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort

      - name: Check formatting
        run: |
          black --check app tests
          isort --check-only app tests

      - name: Create format report
        if: failure()
        run: |
          black --diff app tests > format_report.txt
          isort --diff app tests >> format_report.txt

      - name: Upload format report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: format-report
          path: format_report.txt